### ISSUE TITLE
View registration does not use ViewContractAttribute

### ISSUE THREAD

**Issue by itabaev** [alexeyzimarev/ReactiveUI.Autofac#1]
Views:
```c#
public partial class FooView : UserControl, IViewFor<IFooViewModel>
{
}

[ViewContract("Header")]
public partial class FooHeaderView : UserControl, IViewFor<IFooViewModel>
{
}
```

`[ViewContract("Header")]` is not working.
I have to register a view for the "Header" contract:
```c#
Locator.CurrentMutable.Register<IViewFor<IFooViewModel>>(() => new FooHeaderView(), "Header");
```

How to automatically register a views with contracts?

**Comment by alexeyzimarev** [comment]
Unfortunately, I currently have no support for these attributes. PR is welcomed of course if you want and can fix it :)

**Comment by alexeyzimarev** [comment]
Thanks for the PR! :)
Can you try the dev package and confirm that it works as expected?
https://www.myget.org/feed/az-github/package/nuget/ReactiveUI.Autofac

**Comment by itabaev** [comment]
Works with reactiveui 6.5.2.
Since version 7.0.0, the Contract property of the attribute has become internal :(

**Comment by alexeyzimarev** [comment]
Shall I ask them about it, to consider opening it back?

**Comment by itabaev** [comment]
If it's not hard for you. I will be grateful :)

**Comment by alexeyzimarev** [comment]
https://github.com/reactiveui/ReactiveUI/issues/1440

**Comment by alexeyzimarev** [comment]
@itabaev do you want me to publish a new release package or shall I wait to clarify the issue with RxUI 7 first?

**Comment by itabaev** [comment]
I use RxUI 7 in my project.
So we can wait.
Thanks!

**Comment by alexeyzimarev** [comment]
https://github.com/alexeyzimarev/ReactiveUI/commit/f968a461982acf541f00bb2ebb67fcf76081182c
